### ISSUE TITLE
Add Background Color Option

### ISSUE THREAD

**Issue by mwhiteley16** [timothyjensen/simple-container-block#1]
This block could be improved by adding the background color palette option. There would be no need for any other attributes (like font color) as those would be managed by the blocks inside this container div, but the background color additional would allow to create sections moving down the page with different background colors when the block is set using alignfull, with all nested blocks inside.

**Comment by timothyjensen** [comment]
This is an interesting idea. I wonder, though, how helpful it will be to add only a background color option without adding any padding. Unless there is some padding the background color will butt up against the inner content and won't look right. Because I want to keep this plugin as lean as possible I don't want to enqueue a separate stylesheet, and because of that it will be left up to the user to add padding via CSS or by defining classes on the container. At that point, the user might as well add CSS such as `bg--blue`.

Your thoughts?

**Comment by mwhiteley16** [comment]
Valid point. Looks like other items that you can add background color to (like paragraphs) add the `has-background` class, which triggers the padding, but they are specific to the attribute. So the css is `p.has-background`, so you couldn't just have it add the `has-background` class to trigger the padding. And that padding may not even be what you want.

So based on that, you would need CSS to add the padding...so might as well just use CSS to add the background color as well (or the class as you note).

**Comment by timothyjensen** [comment]
Yeah, I think we're on the same page here so I'll close this out. Thanks for the discussion!
